{
    'name': 'Dentari Lab',
    'version': '18.0.1.3.0',
    'category': 'Dental / Laboratory',
    'summary': 'Dental laboratory work log tracking',
    'depends': ['base', 'mail', 'account', 'digest'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/invoice_data.xml',
        'data/email_templates.xml',
        'report/report_monthly_summary.xml',
        'views/dental_work_log_views.xml',
        'views/wizard_invoice_views.xml',
        'views/wizard_monthly_views.xml',
        'views/digest_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
